version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend

  server:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development-build-stage
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_URL: mongodb+srv://admin:admin@cluster1.afam1.mongodb.net/
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

volumes:
  mongo-data:


networks:
  backend:
    driver: bridge
