export const API_URL = {
	signIn: "/auth/login",
	resendOTP: "/auth/verify/",
	sendResetPasswordEmail: "/auth/reset-password/request",
	verifyOTP: "/auth/verify",
	resetPassword: "/auth/create",
	signUp: "/auth/create",
	getUser: "/users",
	registerKyc: "/users/kyc/register",
	updateKyc: "/users/kyc/update",
	resendKycOtp: "/users/kyc/resend-otp",
	validateKycOtp: "/users/kyc/validate-otp",
	wallet: "/wallets",
	updateBank: "/wallets/save-bank-details",
	walletTransactions: "/wallet/transactions",
	createListings: "/listings/create",
	deleteListing: "/listings/delete",
	changeListingStatus: "/listings/change-status",
	updateListing: "/listings/update",
	listings: "/listings/all",
	listingById: "/listings",
	listingsByUser: "/listings/byUser",
	searchListings: "/listings/search",
	uploadFiles: "/listings/upload",
	categories: "/listings/categories",
	categoriesDetailed: "/listings/categories/detailed",
	stellarWallet: "/stellar/wallets",
	stellarWalletTransactions: "/stellar/wallets/transactions",
    transferXlm: "/stellar/wallets/transfer",
    addCart: "/cart/create",
    addCartMultiple: "/cart/create/multiple",
    getCart: "/cart",
    removeCart: "/cart/remove-item",
    transaction: "/transactions/create",
    getTransactions: "/transactions/byUser",
    getSingleTransaction: "/transactions",
	changeTxStage: "/transactions/update-stage",
	changeTxStatus: "/transactions/update-status",
	reviews: "/reviews/add",
	getTransactionsAnalytics: "/analytics/transactions",
	getSalesAnalytics: "/analytics/sales",
	createMessages: "/chats/new",
	addMessage: (id: string) => `/chats/${id}/messages`,
	getUserMessages: (id: string) => `/chats/all/${id}`,
	getChatMessages: (id: string) => `/chats/${id}`,
	updateUser: "/users/update",
	updateAccountPin: "/users/update-pin",
};
